### ISSUE TITLE
Setting up the GitHub App Bot

### ISSUE THREAD

**Issue by nicolasrouanne** [dkhmelenko/autoapproval#2]
I see you made a [GitHub App](https://github.com/apps/autoapproval) out of this bot 👍 

However, after adding the GitHub App to my organization and repository, setting up with a `.github/autoapproval.yml` file (see below), nothing happens...
FYI I'm trying to set up autoapproval for **dependabot** PRs, related to [this issue](https://github.com/dependabot/feedback/issues/86).

Any clue?

My `.github/autoapproval.yml`:
```yml
from_owner:
  - dependabot-preview
required_labels:
  - dependencies
apply_labels:
  - autoapproved
```

**Comment by dkhmelenko** [comment]
I checked logs and see that the owner created a PR is `dependabot-preview[bot]`. Therefore you have to specify exactly that name in `.github/autoapproval.yml`. This can be the issue.

If you would like to have more control over the behavior of the app (like viewing logs), I would recommend you to deploy it to your own server.

**Comment by nicolasrouanne** [comment]
It's great, it's working 🚀 ❤️ 
So here is my working `.github/autoapproval.yml` configuration file
```yml
from_owner:
  - dependabot-preview[bot]
required_labels:
  - dependencies
apply_labels:
  - autoapproved
```

> Note: I chose to put the `dependencies` label in "required_label" since **dependabot** is currently adding it to any PR

<img width="663" alt="Screenshot 2019-06-24 at 11 15 16" src="https://user-images.githubusercontent.com/12157019/60006770-5dc25b00-9671-11e9-927d-1a4f53309196.png">
