### ISSUE TITLE
Approved comment spammed on PR

### ISSUE THREAD

**Issue by tycrek** [dkhmelenko/autoapproval#484]
Just finished setting this up using your GitHub App for [my project ass](https://github.com/tycrek/ass/pull/81). Opened a test PR and got a ton of comments...

[My Yaml file](https://github.com/tycrek/ass/blob/master/.github/autoapproval.yml) is as follows:

```yaml
from_owner:
  - tycrek
required_labels:
  - tycrek
apply_labels: []
```

The PR in question: https://github.com/tycrek/ass/pull/81

As you can see in the PR, it spammed a ton of "Approved" comments which I don't think is supposed to happen. Any idea what would have caused this?
