### ISSUE TITLE
Error: Cannot read properties of null (reading 'blacklisted_labels')

### ISSUE THREAD

**Issue by vchiapaikeo** [dkhmelenko/autoapproval#753]
I'm having some trouble integrating this action. There seems to be issues around reading the config file which I've copied verbatim from the example and placed at .github/autoapproval.yml. I think we need to provide the additional contents: read permission so that it can read the config.

```
permissions:
  contents: read
  pull-requests: write
```

However, after doing that, I still seem to be runninig into issues:

```
Run dkhmelenko/autoapproval@v1.0
Repo: myorg/reponame
{ name: 'event', id: '3678729916' }
PR: https://github.com/myorg/reponame/pull/1455
{ name: 'event', id: '3678729916' }
Action: opened
{ name: 'event', id: '3678729916' }
Loaded config
{ name: 'event', id: '3678729916' }
Error: Cannot read properties of null (reading 'blacklisted_labels')
{
  name: 'event',
  id: '3678729916',
  err: {
    type: 'TypeError',
    message: "Cannot read properties of null (reading 'blacklisted_labels')",
    stack: "TypeError: Cannot read properties of null (reading 'blacklisted_labels')\n" +
      '    at /home/runner/work/_actions/dkhmelenko/autoapproval/v1.0/dist/index.js:128784:32\n' +
      '    at step (/home/runner/work/_actions/dkhmelenko/autoapproval/v1.0/dist/index.js:128751:[23](https://github.com/etsy/airflow/actions/runs/3678729916/jobs/6222480786#step:2:24))\n' +
      '    at Object.next (/home/runner/work/_actions/dkhmelenko/autoapproval/v1.0/dist/index.js:1[28](https://github.com/etsy/airflow/actions/runs/3678729916/jobs/6222480786#step:2:29)7[32](https://github.com/etsy/airflow/actions/runs/3678729916/jobs/6222480786#step:2:33):53)\n' +
      '    at fulfilled (/home/runner/work/_actions/dkhmelenko/autoapproval/v1.0/dist/index.js:128723:58)',
```

Any idea what the issue might be?

**Comment by dkhmelenko** [comment]
Thanks for the hint adding permissions, I will update Readme file 👍 

Can you show your config file for autoapproval? Do you have a defined `blacklisted_labels`?

**Comment by vchiapaikeo** [comment]
Hey! Yup, I've set it like this:

.github/autoapproval.yml
```yaml
_extends: etsy/github-settings

from_owner:
  - dependabot[bot]

required_labels:
  - dependencies

blacklisted_labels:
  - wip

apply_labels:
  - merge
```

And .github/workflows/auto-approve.yml:
```yaml
name: Auto-Approve

on:
  pull_request:
    types: [opened, reopened, labeled, edited]
  pull_request_review:
    types: [dismissed]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    name: Auto-Approve
    steps:
      - uses: dkhmelenko/autoapproval@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
